apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.060
    profile: false
    max_hamming: 1
    pose_estimation_method: "pnp"
    detector:
      threads: 4
      decimate: 1.0
      blur: 0.8
      refine: true
      sharpening: 0.25
      debug: false
